import { CommandRegistry } from './registry';
import { helpCommand } from './help';
import { clearCommand } from './clear';
import { exitCommand } from './exit';
import { modelCommand } from './model';
import { configCommand } from './config';
import { statusCommand } from './status';
import { planCommand } from './plan';
import { costCommand } from './cost';
import { permissionsCommand } from './permissions';
import { doctorCommand } from './doctor';
import { compactCommand } from './compact';
import { diffCommand } from './diff';
import { reviewCommand } from './review';
import { initCommand } from './init';
import { exportCommand } from './export';
import { mcpCommand } from './mcp';
import { skillCommand } from './skill';
import { hooksCommand } from './hooks';
import { agentCommand } from './agent';
import { batchCommand } from './batch';
import { btwCommand } from './btw';
import { backgroundCommand } from './background';
import { rewindCommand } from './rewind';
import { upgradeCommand } from './upgrade';
import { feedbackCommand } from './feedback';

export function loadBuiltInCommands(registry: CommandRegistry) {
  registry.register(helpCommand);
  registry.register(clearCommand);
  registry.register(exitCommand);
  registry.register(modelCommand);
  registry.register(configCommand);
  registry.register(statusCommand);
  registry.register(planCommand);
  registry.register(costCommand);
  registry.register(permissionsCommand);
  registry.register(doctorCommand);
  registry.register(compactCommand);
  registry.register(diffCommand);
  registry.register(reviewCommand);
  registry.register(initCommand);
  registry.register(exportCommand);
  registry.register(mcpCommand);
  registry.register(skillCommand);
  registry.register(hooksCommand);
  registry.register(agentCommand);
  registry.register(batchCommand);
  registry.register(btwCommand);
  registry.register(backgroundCommand);
  registry.register(rewindCommand);
  registry.register(upgradeCommand);
  registry.register(feedbackCommand);
}
